#!/bin/sh
#
# script install audit scripts to /usr/local/audit
#
# * created: 2012-02-05 Kevin Chan <kefin@makedostudio.com>
# * updated: 2012-02-11 kchan

########################################################################
myname=`basename $0`
OLD_PWD=$PWD
cd "`dirname $0`"
mydir="${PWD%/}"
cd "$OLD_PWD"
########################################################################


########################################################################
# helper functions
########################################################################

error()
{
    [ "$1" ] && echo >&2 "###" "$@"
    exit 1
}

check_root_user()
{
    if [ `id -u` != 0 ]; then
        error "Script must be run by root."
    fi
}

makedir()
{
    [ "$1" ] && {
        [ ! -d "$1" ] && mkdir -p "$1"
    }
}

########################################################################

### set vars

BASE_DIR_NAME="audit"
DEST_DIR="/usr/local/$BASE_DIR_NAME"
DIRS="bin conf logs"
SCRIPTS="\
    bin/run_audit \
    bin/utils \
    bin/dummy \
    bin/lsat \
    bin/lynis \
    bin/chkrootkit \
    bin/rkhunter"
CONFIG_TEMPLATES="conf/run_audit.conf.template"
CONFIG="conf/run_audit.conf"

### check user permissions

check_root_user


### install scripts

if [ $# -eq 1 ]; then
    answer="$1"
else
    printf "Do you want to install the backup scripts in $DEST_DIR (Y/N)? "
    read answer
fi

case $answer in
    y|Y|yes|Yes|YES)
        ;;
    n|N|no|No|NO)
        echo "# Cancelled."
        exit 1
        ;;
    *)
        echo "# Unknown answer. Cancelled."
        exit 1
        ;;
esac


makedir "$DEST_DIR"
echo "# created directory $DEST_DIR"

for d in $DIRS
do
    target="${DEST_DIR}/$d"
    makedir "$target" && \
    echo "# created directory $target"
done

for file in $SCRIPTS $CONFIG_TEMPLATES
do
    dst="${DEST_DIR}/$file"
    cp "${mydir}/$file" "$dst" && \
        chmod +x "$dst" && \
        echo "# $file installed as $dst"
done

# create configuration file if it doesn't exist
config="${DEST_DIR}/$CONFIG"
if [ ! -f "$config" ] && [ -f "${config}.template" ]; then
    cp "${config}.template" "$config"
    echo "# created configuration file: $config"
    echo "# please edit according to your server and admin settings"
fi

exit
