#!/bin/sh
#
# installation script for audit helpers
# * script are installed in /usr/local/audit/bin
# * configuration files are installed in /etc/audit
#
# * created: 2012-02-05 Kevin Chan <kefin@makedostudio.com>
# * updated: 2012-12-23 kchan

########################################################################
myname=$(basename "$0")
OLD_PWD=$PWD
cd $(dirname "$0")
mydir=${PWD%/}
cd "$OLD_PWD"
########################################################################


########################################################################
# helper functions

error()
{
    [ "$1" ] && echo >&2 "###" "$@"
    exit 1
}

check_root_user()
{
    [ $(id -u) = 0 ] || error "Script must be run by root."
}

makedir()
{
    [ "$1" ] && [ ! -d "$1" ] && mkdir -p "$1"
}


########################################################################

### set vars

PACKAGE_NAME="audit"
SRC_DIR="$mydir"
SCRIPT_SRC_DIR="${SRC_DIR}/bin"
CONFIG_SRC_DIR="${SRC_DIR}/conf"
SCRIPT_DST_DIR="/usr/local/${PACKAGE_NAME}/bin"
CONFIG_DST_DIR="/etc/${PACKAGE_NAME}"
INSTALL_DIRS="$SCRIPT_DST_DIR $CONFIG_DST_DIR"
SCRIPTS="\
    run_audit \
    utils \
    dummy \
    lsat \
    lynis \
    chkrootkit \
    rkhunter \
    tripwire"
TEMPLATE_SUFFIX=".template"
CONFIG_TEMPLATES="run_audit.conf${TEMPLATE_SUFFIX}"
CONFIGS="run_audit.conf"
SCRIPT_PERMS="700"
CONFIG_PERMS="600"


### check user permissions

check_root_user


### install scripts

if [ $# -eq 1 ]; then
    answer="$1"
else
    printf "Do you want to install the backup scripts in $DST_DIR (Y/N)? "
    read answer
fi

case $answer in
    [Yy]|[Yy][Ee][Ss]|-[Yy]|-[Yy][Ee][Ss]|--[Yy][Ee][Ss])
        ;;
    [Nn]|[Nn][Oo]|-[Nn]|-[Nn][Oo]|--[Nn][Oo])
        echo "# Cancelled."
        exit 1
        ;;
    *)
        echo "# Unknown answer. Cancelled."
        exit 1
        ;;
esac


errors=0

for d in $INSTALL_DIRS
do
    if [ ! -d "$d" ]; then
        makedir "$d"
        echo "# Created directory $d"
    fi
done

for file in $SCRIPTS
do
    src="${SCRIPT_SRC_DIR}/$file"
    dst="${SCRIPT_DST_DIR}/$file"
    install -m "$SCRIPT_PERMS" "$src" "$dst" \
        && echo "# $file installed as $dst"
done

for file in $CONFIG_TEMPLATES
do
    src="${CONFIG_SRC_DIR}/$file"
    dst="${CONFIG_DST_DIR}/$file"
    install -m "$CONFIG_PERMS" "$src" "$dst" \
        && echo "# $file installed as $dst"
done


# create configuration file if it doesn't exist

for file in $CONFIGS
do
    src="${CONFIG_SRC_DIR}/${file}${TEMPLATE_SUFFIX}"
    dst="${CONFIG_DST_DIR}/${file}"
    if [ ! -f "$src" ]; then
        echo >&2 "### Cannot find configuration template: $src"
        errors=$((errors + 1))
    else
        if [ ! -f "$dst" ]; then
            install -m "$CONFIG_PERMS" "$src" "$dst" \
                && {
                    echo "# Created configuration file:  $dst"
                    echo "# Please edit according to your settings."
                }
        fi
    fi
done

exit $errors
